### PR TITLE
Support for an action that has one or more valid non-zero exit code

### PR DESCRIPTION
**Pull request by richard-fine**
Various tools that we want to run (e.g. Robocopy) emit non-zero return values in some successful situations. This PR adds support for nodes to specify their acceptable return values (defaulting to 0 if the node does not specify).

### CODE REVIEW

**Comment by aras-p** [comment]
Hmm not sold on the usefulness of this. This is for a "very uncommon" case, but makes everything a _tiny bit_ slower (larger data structures, more memory, slightly slower DAG loading etc.). Not by much, but every tiny bit adds up eventually.

**Comment by aras-p** [comment]
I guess fine, if you can find more than just the `robocopy` case that would need it

**Comment by richard-fine** [comment]
Going to delay merging this until I find use case #2.

**Comment by richard-fine** [comment]
Don't think this is going to go anywhere.

**Pull request closed without merging**
